services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
       MYSQL_DATABASE : 'db'
       MYSQL_ROOT_PASSWORD : 'root'
    ports:
      - '3307:3306'

  pythonapp:
    build: ./python/
    command: sh -c "python3 ./main.py"
    depends_on:
      - mysql
    ports:
      - "5000:5000"
